[build]
  command = "npm run build"
  publish = "public"
  functions = "src/functions"

[build.environment]
  NODE_ENV = "20.14.0"

[dev]
  command = "npm run start"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
